import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  vi: {
    // Settings
    settings: "Cài đặt",
    profile: "Hồ sơ",
    language: "Ngôn ngữ",
    currency: "Tiền tệ",
    data: "Dữ liệu & Sao lưu",
    help: "Trợ giúp",
    about: "Giới thiệu",
    logout: "Đăng xuất",
    save: "Lưu",
    cancel: "Hủy",
    edit: "Chỉnh sửa",
    name: "Tên",
    email: "Email",
    selectCurrency: "Chọn tiền tệ",
    exchangeRate: "Tỷ giá: 1 USD =",
    default: "Mặc định:",
    confirm: "Xác nhận",
    selectLanguage: "Chọn ngôn ngữ",
    vietnamese: "Tiếng Việt",
    english: "English",
    deleteAllData: "Xóa tất cả dữ liệu",
    exportData: "Xuất dữ liệu",
    exportSimpleReport: "Xuất báo cáo đơn giản",
    // Wallets
    myWallets: "Ví của tôi",
    totalAssets: "Tổng tài sản",
    payment: "Thanh toán",
    monthlyExpense: "Chi tiêu tháng này",
    paymentWallets: "Ví thanh toán",
    noWallets: "Chưa có ví nào",
    createFirstWallet: "Tạo ví đầu tiên để bắt đầu quản lý tài chính",
    income: "Thu nhập",
    expense: "Chi tiêu",
    // Dashboard & Sidebar
    budget: "Ngân sách",
    wallet: "Ví",
    addTransaction: "Thêm giao dịch",
    personalSpendingManagement: "Quản lý chi tiêu cá nhân",
    trackAndAnalyzeMonthly: "Theo dõi và phân tích thu chi hàng tháng",
    savings: "Tiết kiệm",
    savingsRate: "Tỷ lệ tiết kiệm",
    expensesByCategory: "Chi tiêu theo danh mục",
    incomeAndExpensesLast6Months: "Thu chi 6 tháng gần đây",
    transactions: "Giao dịch",
    searchTransactions: "Tìm kiếm giao dịch...",
    all: "Tất cả",
    byDate: "Theo ngày",
    user: "Người dùng",
    // Wallet Management
    walletManagement: "Quản lý ví",
    trackAndManageWallets: "Theo dõi và quản lý các ví tiền của bạn",
    createNewWallet: "Tạo ví mới",
    transferBetweenWallets: "Chuyển tiền giữa các ví",
    quickUpdateBalance: "Cập nhật số dư nhanh",
    eWallet: "Ví điện tử",
    bankCard: "Thẻ ngân hàng",
    cash: "Tiền mặt",
    defaultWallet: "Mặc định",
    recentTransactions: "Giao dịch gần đây",
    lastUpdate: "Lần cuối cập nhật:",
    newBalance: "Số dư mới",
    updateBalance: "CẬP NHẬT SỐ DƯ",
    updateBalanceTitle: "Cập nhật số dư hiện tại trong ví",
    balanceInputTip:
      "Nhập số dư mới cho ví. Bạn có thể dùng nút xóa để xoá nhanh các ký tự.",
    clearAll: "Xóa hết",
    youWantToTransfer: "Bạn muốn chuyển đi",
    selectWallet: "Chọn ví",
    addDescription: "Thêm mô tả...",
    transferSuccess: "Chuyển tiền thành công!",
    invalidAmount: "Vui lòng nhập số tiền hợp lệ",
    pleaseSelectWallet: "Vui lòng chọn ví",
    cannotTransferToSameWallet: "Không thể chuyển tiền cho chính ví đó",
    insufficientBalance: "Số dư ví không đủ",
    transferError: "Có lỗi xảy ra khi chuyển tiền",
    balanceCannotBeNegative: "Số dư không thể âm",
    pleaseSelectWalletForUpdate: "Vui lòng chọn ví",
    updateBalanceSuccess: "Cập nhật số dư thành công!",
    updateBalanceError: "Có lỗi xảy ra khi cập nhật số dư",
    // Wallet Modal
    createPaymentWallet: "Tạo ví thanh toán",
    updateWalletBalance: "Cập nhật số dư ví",
    walletName: "Tên của ví này",
    currentBalanceInWallet: "Hiện tại số dư trong ví của bạn là bao nhiêu?",
    balanceInputHelper:
      "Bạn nhập số tiền càng chính xác thì chúng tôi có thể giúp bạn cập nhật ngân sách càng chính xác hơn.",
    defaultWalletDescription:
      "Ví mặc định là ví sẽ được mặc định lựa chọn khi bạn tạo các giao dịch.",
    setAsDefaultWallet: "Đặt làm ví mặc định",
    saveNewWallet: "Lưu ví mới",
    saveNewWalletButton: "LƯU VÍ MỚI",
    updateWallet: "Cập nhật ví",
    updateWalletButton: "CẬP NHẬT VÍ",
    changeIcon: "Thay đổi biểu tượng",
    selectIcon: "Chọn icon",
    saveWalletError: "Có lỗi xảy ra khi lưu ví. Vui lòng thử lại.",
    creditCard: "Thẻ tín dụng",
    bank: "Ngân hàng",
    coins: "Tiền xu",
    target: "Mục tiêu",
    calendar: "Lịch",
    // Analytics
    analysis: "Phân tích",
    analysisDetails: "Chi tiết thu chi theo danh mục",
    spendingAnalysis: "Phân tích chi tiêu",
    incomeAnalysis: "Phân tích thu nhập",
    byCategory: "Theo danh mục",
    totalSpending: "Tổng chỉ tiêu",
    totalIncome: "Tổng thu nhập",
    saved: "Tiết kiệm được",
    noExpenseTransactions: "Chưa có giao dịch chi tiêu",
    noIncomeTransactions: "Chưa có giao dịch thu nhập",
    trend5Months: "Xu hướng 5 tháng",
    noData: "Chưa có dữ liệu",
    addTransactionToViewChart: "Thêm giao dịch để xem biểu đồ",
    add: "Thêm",
    // Budget Allocation
    allocateMoneyToBudget: "Phân chia tiền vào ngân sách",
    currentlyAvailable: "Đang có",
    remaining: "Còn lại",
    spent: "Đã tiêu:",
    saveAllAllocations: "LƯU TẤT CẢ PHÂN BỐ",
    other: "Khác",
    allocationExceedsBalance: "Số tiền phân bổ vượt quá số dư khả dụng",
    // Category Group Manager
    manageCategoryGroups: "Quản lý nhóm danh mục",
    createCategoryGroup: "Tạo nhóm danh mục",
    addCategory: "Thêm danh mục",
    categoryGroupTip:
      'Bạn có thể thêm nhanh từ mẫu có sẵn. Các danh mục đã có sẽ hiển thị nhãn "Đã có".',
    deleteCategoryError: "Có lỗi xảy ra khi xóa danh mục",
    sort: "Sắp xếp",
    deleteCategory: "Xoá danh mục",
    alreadyAdded: "Đã có",
    // Help Center
    helpCenter: "Trung tâm trợ giúp",
    helpCenterContent:
      "- Thiết lập danh mục và nhóm danh mục để quản lý ngân sách theo từng mục.\n- Phân bổ ngân sách trong phần Chỉnh sửa ngân sách.\n- Cập nhật số dư ví và thêm giao dịch để theo dõi thu/chi.",
    restartGuide: "Bắt đầu lại hướng dẫn",
    restartGuideDescription:
      "Khởi chạy lại tour hướng dẫn từng bước dành cho người mới.",
    // Onboarding
    welcomeToFinanceTracker: "Chào mừng đến với Finance Tracker",
    smartPersonalFinanceApp: "Ứng dụng quản lý tài chính cá nhân thông minh",
    smartSpendingManagement: "Quản lý chi tiêu thông minh",
    trackAndAnalyzeIncomeExpenses:
      "Theo dõi và phân tích thu chi một cách dễ dàng",
    enterIncomeAndExpenses: "Nhập thu nhập và chi tiêu",
    recordAllDailyTransactions:
      "Ghi lại tất cả các khoản thu chi hàng ngày để biết bạn đang tiêu tiền vào đâu.",
    categorizeByCategory: "Phân loại theo danh mục",
    divideMoneyIntoCategories:
      "Chia tiền vào các danh mục cụ thể như Ăn uống, Đi lại, Giải trí...",
    viewChartsAndStatistics: "Xem biểu đồ và thống kê",
    analyzeSpendingThroughCharts:
      "Phân tích chi tiêu qua biểu đồ trực quan, dễ hiểu.",
    keyFeatures: "Tính năng chính",
    simpleIncomeExpenseManagement: "Quản lý thu chi đơn giản",
    visualEasyToUnderstandCharts: "Biểu đồ trực quan, dễ hiểu",
    filterAndSortTransactions: "Lọc và sắp xếp giao dịch",
    manageMultipleWallets: "Quản lý nhiều ví tiền",
    startNow: "Bắt đầu ngay",
    zeroBasedBudgetingMethod: "Phương pháp lập ngân sách dựa trên con số không",
    incomeMinusExpensesEqualsZero: "Thu Nhập - Chi Tiêu = 0",
    everyDollarMustBeAssigned:
      'Mọi đồng tiền kiếm được đều phải được "giao việc" trước khi bạn thực sự tiêu nó.',
    createEnvelopes: 'Tạo các "Phong bì"',
    divideMoneyIntoSpecificCategories:
      "Chia tiền vào các danh mục cụ thể như Ăn uống, Đi lại, Tiết kiệm...",
    completeControl: "Kiểm soát hoàn toàn",
    knowExactlyWhereMoneyGoes:
      "Bạn biết chính xác tiền đi đâu và có thể điều chỉnh linh hoạt.",
    benefitsOfSmartSpendingManagement:
      "Lợi ích của Quản lý chi tiêu thông minh",
    betterSpendingControl: "Kiểm soát chi tiêu tốt hơn",
    saveMore: "Tiết kiệm nhiều hơn",
    achieveFinancialGoals: "Đạt được mục tiêu tài chính",
    reduceFinancialStress: "Giảm stress về tiền bạc",
    strengthenFinancialDiscipline: "Tăng cường kỷ luật tài chính",
    betterFuturePlanning: "Lập kế hoạch tương lai tốt hơn",
    readyToStartFinancialJourney: "Sẵn sàng bắt đầu hành trình tài chính?",
    startSmartFinancialManagement:
      "Hãy bắt đầu quản lý tài chính thông minh với Finance Tracker",
    // Category Selection
    selectExpenseCategories: "Chọn danh mục chi tiêu",
    categoriesSelected: "danh mục đã chọn",
    selectYourExpenseCategories: "Chọn danh mục chi tiêu của bạn",
    incomeCategoriesAutoCreated:
      "Danh mục thu nhập (Lương, Thưởng, Đầu tư...) sẽ được tạo tự động.",
    canEditLater: "Bạn có thể chỉnh sửa bất kì lúc nào sau này.",
    template1FinanceTracker: "Mẫu 1: Finance Tracker Style",
    template1Description: "Phong cách quản lý tài chính linh hoạt và hiện đại",
    template2_50_30_20: "Mẫu 2: 50/30/20",
    template2Description:
      "Phương pháp phân bổ ngân sách 50% nhu cầu, 30% mong muốn, 20% tiết kiệm",
    selectAll: "Tất cả",
    deselectAll: "Bỏ chọn",
    continueButton: "TIẾP TỤC",
    readyToContinue: "Sẵn sàng tiếp tục?",
    skipStepHint:
      "Bạn có thể bỏ qua bước này và tạo danh mục sau trong ứng dụng",
    selectedCategoriesCount:
      "Bạn đã chọn {count} danh mục để bắt đầu quản lý tài chính",
    goBack: "Quay lại",
    // Category Names (for templates)
    categoryRent: "Tiền nhà",
    categoryBills: "Hoá đơn",
    categoryFood: "Ăn uống",
    categoryTransportation: "Đi lại",
    categoryChildren: "Con cái",
    categoryPets: "Thú cưng",
    categoryDebt: "Trả nợ/khoản vay",
    categoryHealthcare: "Khám bệnh/thuốc men",
    categoryInsurance: "Bảo hiểm nhân thọ",
    categoryCarMaintenance: "Bảo trì xe",
    categoryGifts: "Quà tặng, hiếu hỉ",
    categoryEducation: "Học phí, khoá học online",
    categoryShopping: "Shopping",
    categoryMassage: "Massage",
    categorySpa: "Spa",
    categoryHomeDecoration: "Trang hoàng nhà cửa",
    categoryShortTrips: "Du lịch ngắn ngày",
    categoryBuyHouse: "Mua nhà",
    categoryBuyCar: "Mua xe",
    categoryHomeRepair: "Sửa nhà",
    categoryEquipmentUpgrade: "Nâng cấp thiết bị, đồ nghề",
    categoryHousing: "Nhà ở",
    categoryDailyFood: "Ăn uống hằng ngày",
    categoryMandatoryInsurance: "Bảo hiểm bắt buộc",
    categoryBasicMedicine: "Thuốc men cơ bản",
    categoryDiningOut: "Ăn ngoài/cafe",
    categoryShoppingEntertainment: "Shopping/giải trí",
    categoryTravel: "Du lịch",
    categorySpaMassage: "Spa, massage",
    categoryPersonalHobbies: "Sở thích cá nhân",
    categoryEmergencyFund: "Quỹ khẩn cấp",
    categoryLongTermInvestment: "Đầu tư dài hạn",
    categoryEquipmentUpgradeShort: "Nâng cấp thiết bị",
    categorySelfDevelopment: "Học tập / phát triển bản thân",
    // Category Groups
    groupMandatoryExpenses: "Chi phí bắt buộc",
    groupIrregularExpenses: "Chi phí không thường xuyên",
    groupMyJoys: "Niềm vui của tôi",
    groupLongTermInvestment: "Đầu tư dài hạn",
    groupEssentialNeeds: "Nhu cầu thiết yếu (50%)",
    groupWants: "Mong muốn (30%)",
    groupSavingsInvestment: "Tiết kiệm & Đầu tư (20%)",
    groupIncome: "Thu nhập",
    // Income Categories
    incomeSalary: "Lương",
    incomeBonus: "Thưởng",
    incomeInvestment: "Đầu tư",
    incomeOther: "Thu nhập khác",
    // Tour Guide
    tourStep1ManageGroups: "Quản lý nhóm và thêm danh mục từ mẫu có sẵn.",
    tourStep2BudgetList: "Xem và chỉnh sửa ngân sách từng danh mục tại đây.",
    tourStep3WalletUpdate: "Cập nhật số dư ví để số liệu chính xác.",
    tourStep4AddTransaction: "Thêm giao dịch đầu tiên của bạn.",
    tourStep5CreateWallet:
      "Tạo ví mới để quản lý tài chính của bạn một cách hiệu quả.",
    finish: "Hoàn tất",
    next: "Tiếp tục",
    skip: "Bỏ qua",
    // Landing Page & Login
    login: "Đăng nhập",
    register: "Đăng ký",
    registerSubtitle: "Tạo tài khoản mới để bắt đầu",
    registerFree: "Đăng ký miễn phí",
    registerNow: "Đăng ký ngay",
    registering: "Đang đăng ký...",
    registerFailed: "Đăng ký thất bại",
    fullName: "Họ và tên",
    confirmPassword: "Xác nhận mật khẩu",
    nameRequired: "Vui lòng nhập tên",
    nameMinLength: "Tên quá ngắn",
    confirmPasswordRequired: "Vui lòng xác nhận mật khẩu",
    passwordsDontMatch: "Mật khẩu không khớp",
    alreadyHaveAccount: "Đã có tài khoản?",
    loginNow: "Đăng nhập ngay",
    placeholderName: "Nguyễn Văn A",
    landingSecurityBadge: "Bảo mật & Miễn phí 100%",
    landingHeroTitle: "Quản lý tài chính",
    landingHeroSubtitle: "thông minh hơn",
    landingHeroDescription:
      "Theo dõi chi tiêu, phân tích xu hướng và đạt được mục tiêu tài chính của bạn. Tất cả trong một ứng dụng đơn giản, dễ sử dụng.",
    landingStartFree: "Bắt đầu ngay - Miễn phí",
    landingExampleIncome: "Thu nhập tháng này",
    landingExampleExpense: "Chi tiêu tháng này",
    landingFeaturesTitle: "Tính năng nổi bật",
    landingFeaturesSubtitle: "Mọi thứ bạn cần để quản lý tài chính hiệu quả",
    landingFeature1Title: "Theo dõi thu chi",
    landingFeature1Desc:
      "Ghi lại mọi khoản thu nhập và chi tiêu một cách dễ dàng, nhanh chóng",
    landingFeature2Title: "Phân tích chi tiêu",
    landingFeature2Desc:
      "Biểu đồ trực quan giúp bạn hiểu rõ các khoản chi tiêu của mình",
    landingFeature3Title: "Mục tiêu tiết kiệm",
    landingFeature3Desc: "Đặt mục tiêu tài chính và theo dõi tiến độ đạt được",
    landingFeature4Title: "Giao dịch định kỳ",
    landingFeature4Desc:
      "Tự động ghi nhận các khoản thu chi lặp lại hàng tháng",
    landingFeature5Title: "Xu hướng tài chính",
    landingFeature5Desc:
      "Xem xu hướng thu chi theo thời gian để có quyết định tốt hơn",
    landingFeature6Title: "Xuất báo cáo",
    landingFeature6Desc: "Tải xuống dữ liệu dưới dạng CSV hoặc PDF để lưu trữ",
    landingBenefit1: "Miễn phí 100% - Không có phí ẩn",
    landingBenefit2: "Giao diện đẹp, dễ sử dụng",
    landingBenefit3: "Bảo mật thông tin tuyệt đối",
    landingBenefit4: "Truy cập mọi lúc, mọi nơi",
    landingBenefit5: "Cập nhật tính năng liên tục",
    landingBenefit6: "Hỗ trợ đa thiết bị",
    landingWhyUsTitle: "Tại sao chọn chúng tôi?",
    landingCTATitle: "Sẵn sàng bắt đầu hành trình tài chính của bạn?",
    landingCTADescription:
      "Tham gia cùng hàng nghìn người dùng đã cải thiện tài chính của họ",
    landingCTAButton: "Đăng ký miễn phí ngay",
    landingFooterText: "Quản lý tài chính thông minh.",
    loginSubtitle: "Quản lý tài chính cá nhân của bạn",
    password: "Mật khẩu",
    invalidEmail: "Email không hợp lệ",
    emailRequired: "Vui lòng nhập email",
    passwordRequired: "Vui lòng nhập mật khẩu",
    passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
    passwordStrengthRequirement:
      "Mật khẩu phải chứa ít nhất 1 chữ hoa (A-Z), 1 chữ thường (a-z) và 1 số (0-9). Ví dụ: MyPass123",
    passwordTooWeak:
      "Mật khẩu quá yếu. Vui lòng sử dụng mật khẩu có chữ hoa, chữ thường và số để tăng tính bảo mật.",
    loginFailed: "Đăng nhập thất bại",
    loggingIn: "Đang đăng nhập...",
    resetPassword: "Đặt lại mật khẩu",
    sendCodeToEmail: "Gửi mã về email",
    sendingCode: "Đang gửi mã...",
    verificationCode: "Mã xác thực (6 số)",
    newPassword: "Mật khẩu mới",
    confirmReset: "Xác nhận đặt lại",
    verificationCodeSent:
      "Đã gửi mã xác thực về email. Vui lòng kiểm tra hộp thư.",
    resetPasswordSuccess: "Đặt lại mật khẩu thành công.",
    resetPasswordFailed: "Đặt lại mật khẩu thất bại",
    sendCodeFailed: "Gửi mã thất bại",
    or: "Hoặc",
    noAccountYet: "Chưa có tài khoản?",
    googleOAuthNotConfigured:
      "Google OAuth chưa được cấu hình. Vui lòng liên hệ quản trị viên.",
    googleSignInInitError:
      "Không thể khởi tạo Google Sign-In. Vui lòng tải lại trang.",
    // Transaction List
    transactionCount: "Giao dịch",
    byAmount: "Theo số tiền",
    confirmDeleteTransaction: "Bạn có chắc chắn muốn xóa giao dịch này?",
    // Budget Screen
    expenseManagement: "Quản lý chi tiêu",
    trackPersonalIncomeExpenses: "Theo dõi thu chi cá nhân",
    statisticalChart: "Biểu đồ thống kê",
    editBudgetAllocation: "Chỉnh sửa phân bổ ngân sách",
    budgetAllocationSuccess: "Phân bổ ngân sách thành công!",
    budgetAllocationError: "Có lỗi xảy ra khi lưu phân bổ ngân sách",
    updateBudgetSuccess: "Cập nhật ngân sách thành công!",
    updateBudgetError: "Có lỗi xảy ra khi cập nhật ngân sách",
    initializeCategoriesError:
      "Có lỗi xảy ra khi khởi tạo danh mục. Vui lòng thử lại.",
    noExpenseData: "Chưa có dữ liệu chi tiêu",
    navigateTo: "Chuyển đến",
    // Quick Action Modal
    whatDoYouWantToCreate: "Bạn muốn tạo gì?",
    transfer: "Chuyển tiền",
    // Wallet Empty States
    createWalletToStart: "Tạo ví để bắt đầu quản lý tài chính",
    createFirstWalletButton: "Tạo ví đầu tiên",
    // Wallet Prompt Modal
    walletPromptTitle: "Tạo ví đầu tiên",
    startManagingFinances: "Bắt đầu quản lý tài chính",
    walletPromptDescription:
      "Để thêm giao dịch, bạn cần tạo ít nhất một ví. Ví giúp bạn tổ chức và theo dõi số tiền của mình.",
    manageMultipleWalletsTitle: "Quản lý nhiều ví",
    manageMultipleWalletsDesc: "Tạo nhiều ví cho các mục đích khác nhau",
    trackBalanceTitle: "Theo dõi số dư",
    trackBalanceDesc: "Xem số dư hiện tại của từng ví một cách dễ dàng",
    recordTransactionsTitle: "Ghi chép giao dịch",
    recordTransactionsDesc:
      "Sau khi có ví, bạn có thể bắt đầu thêm giao dịch thu chi",
    laterButton: "Để sau",
    createWalletNow: "Tạo ví ngay",
    // Budget Screen
    editBudget: "Chỉnh sửa ngân sách",
    categoriesCount: "danh mục",
    allocated: "Đã phân bổ:",
    budgetNotSet: "Chưa thiết lập ngân sách",
    remainingLabel: "Còn:",
    noCategoriesCreated: "Chưa có danh mục nào được tạo",
    createCategoriesToStart:
      "Tạo danh mục để bắt đầu quản lý ngân sách theo Zero-Based Budgeting",
    createNewCategory: "Tạo danh mục mới",
    selectFromTemplate: "Chọn từ mẫu có sẵn",
    noCategoriesYet: "Chưa có danh mục nào. Vui lòng tạo danh mục trước.",
    // Transaction Modal
    selectCategory: "Chọn danh mục",
    selectWallet: "Chọn ví",
    enterAmount: "Nhập số tiền",
    yourCategories: "Danh mục của bạn",
    pleaseCreateWalletAndCategory:
      "Vui lòng tạo ví và danh mục trước khi thêm giao dịch",
    addTransaction: "Thêm giao dịch",
    editTransaction: "Chỉnh sửa giao dịch",
    saveTransaction: "Lưu giao dịch",
    updateTransaction: "Cập nhật giao dịch",
    deleteTransaction: "Xóa giao dịch",
    note: "Ghi chú",
    addNoteForTransaction: "Thêm ghi chú cho giao dịch...",
    loadingData: "Đang tải dữ liệu...",
    clearAll: "Xóa hết",
    update: "Cập nhật",
    save: "Lưu",
    // Wallet Types
    mainWallet: "Ví chính",
    bankCard: "Thẻ ngân hàng",
    eWallet: "Ví điện tử",
    gold: "Vàng",
    creditCard: "Thẻ tín dụng",
    loans: "Các khoản vay",
    // Date Picker
    thisMonth: "Tháng này",
    previousMonth: "Tháng trước",
    // Settings Screen
    dataAndBackup: "Dữ liệu & Sao lưu",
    deleteAllDataWarning:
      "Xóa toàn bộ ví, danh mục, giao dịch và ngân sách. Hành động này không thể hoàn tác.",
    accountInformation: "Thông tin tài khoản",
    editPersonalInformation: "Chỉnh sửa thông tin cá nhân",
    contactUs: "Liên hệ chúng tôi",
    supportAndFeedback: "Hỗ trợ và phản hồi",
    userGuide: "Hướng dẫn sử dụng",
    faqAndDocuments: "FAQ và tài liệu",
    thisMonthOption: "Tháng này",
    thisYear: "Năm nay",
    custom: "Tùy chọn",
    to: "đến",
    exportTransactions: "Xuất giao dịch",
    exportCategories: "Xuất danh mục",
    exportWallets: "Xuất ví",
    exportReports: "Xuất báo cáo",
    yourName: "Tên của bạn",
    saveButton: "Lưu",
    cancelButton: "Hủy",
    noDataToExport: "Không có dữ liệu để xuất",
    confirmLogout: "Bạn có chắc chắn muốn đăng xuất?",
    updateProfileError: "Có lỗi xảy ra khi lưu thông tin. Vui lòng thử lại.",
    deleteDataWarning:
      "⚠️ CẢNH BÁO\n\nBạn có chắc chắn muốn xóa TẤT CẢ dữ liệu tài chính?\n\nHành động này sẽ:\n• Xóa tất cả ví, danh mục, giao dịch\n• Xóa tất cả ngân sách và thống kê\n• KHÔNG THỂ HOÀN TÁC\n\nNhập 'XÓA' để xác nhận:",
    deleteDataConfirmCode: "XÓA",
    deleteDataError: "Có lỗi xảy ra khi xóa dữ liệu. Vui lòng thử lại.",
    deleteDataConfirmInvalid: "Xác nhận không đúng. Hủy bỏ xóa dữ liệu.",
    // Common
    close: "Đóng",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
  },
  en: {
    // Settings
    settings: "Settings",
    profile: "Profile",
    language: "Language",
    currency: "Currency",
    data: "Data & Backup",
    help: "Help",
    about: "About",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    name: "Name",
    email: "Email",
    selectCurrency: "Select Currency",
    exchangeRate: "Exchange Rate: 1 USD =",
    default: "Default:",
    confirm: "Confirm",
    selectLanguage: "Select Language",
    vietnamese: "Vietnamese",
    english: "English",
    deleteAllData: "Delete All Data",
    exportData: "Export Data",
    exportSimpleReport: "Export Simple Report",
    // Wallets
    myWallets: "My Wallets",
    totalAssets: "Total Assets",
    payment: "Payment",
    monthlyExpense: "Monthly Expense",
    paymentWallets: "Payment Wallets",
    noWallets: "No wallets yet",
    createFirstWallet: "Create your first wallet to start managing finances",
    income: "Income",
    expense: "Expense",
    // Dashboard & Sidebar
    budget: "Budget",
    wallet: "Wallet",
    addTransaction: "Add Transaction",
    personalSpendingManagement: "Personal Spending Management",
    trackAndAnalyzeMonthly: "Track and analyze monthly income and expenses",
    savings: "Savings",
    savingsRate: "Savings Rate",
    expensesByCategory: "Expenses by Category",
    incomeAndExpensesLast6Months: "Income and Expenses (Last 6 Months)",
    transactions: "Transactions",
    searchTransactions: "Search transactions...",
    all: "All",
    byDate: "By Date",
    user: "User",
    // Wallet Management
    walletManagement: "Wallet Management",
    trackAndManageWallets: "Track and manage your money wallets",
    createNewWallet: "Create New Wallet",
    transferBetweenWallets: "Transfer Between Wallets",
    quickUpdateBalance: "Quick Update Balance",
    eWallet: "E-wallet",
    bankCard: "Bank card",
    cash: "Cash",
    defaultWallet: "Default",
    recentTransactions: "Recent Transactions",
    lastUpdate: "Last updated:",
    newBalance: "New Balance",
    updateBalance: "UPDATE BALANCE",
    updateBalanceTitle: "Update current balance in wallet",
    balanceInputTip:
      "Enter new balance for wallet. You can use the delete button to quickly clear characters.",
    clearAll: "Clear All",
    youWantToTransfer: "You want to transfer",
    selectWallet: "Select wallet",
    addDescription: "Add description...",
    transferSuccess: "Transfer successful!",
    invalidAmount: "Please enter a valid amount",
    pleaseSelectWallet: "Please select wallet",
    cannotTransferToSameWallet: "Cannot transfer to the same wallet",
    insufficientBalance: "Insufficient wallet balance",
    transferError: "An error occurred while transferring",
    balanceCannotBeNegative: "Balance cannot be negative",
    pleaseSelectWalletForUpdate: "Please select wallet",
    updateBalanceSuccess: "Balance updated successfully!",
    updateBalanceError: "An error occurred while updating balance",
    // Wallet Modal
    createPaymentWallet: "Create Payment Wallet",
    updateWalletBalance: "Update Wallet Balance",
    walletName: "Name of this wallet",
    currentBalanceInWallet: "What is the current balance in your wallet?",
    balanceInputHelper:
      "The more accurate the amount you enter, the more accurately we can help you update your budget.",
    defaultWalletDescription:
      "The default wallet is the wallet that will be selected by default when you create transactions.",
    setAsDefaultWallet: "Set as default wallet",
    saveNewWallet: "Save new wallet",
    saveNewWalletButton: "SAVE NEW WALLET",
    updateWallet: "Update wallet",
    updateWalletButton: "UPDATE WALLET",
    changeIcon: "Change icon",
    selectIcon: "Select icon",
    saveWalletError: "An error occurred while saving wallet. Please try again.",
    creditCard: "Credit Card",
    bank: "Bank",
    coins: "Coins",
    target: "Target",
    calendar: "Calendar",
    // Analytics
    analysis: "Analysis",
    analysisDetails: "Detailed income and expenditure by category",
    spendingAnalysis: "Spending Analysis",
    incomeAnalysis: "Income Analysis",
    byCategory: "By Category",
    totalSpending: "Total Spending",
    totalIncome: "Total Income",
    saved: "Saved",
    noExpenseTransactions: "No expense transactions yet",
    noIncomeTransactions: "No income transactions yet",
    trend5Months: "5 Month Trend",
    noData: "No data yet",
    addTransactionToViewChart: "Add transactions to view chart",
    add: "Add",
    // Budget Allocation
    allocateMoneyToBudget: "Allocate Money to Budget",
    currentlyAvailable: "Currently Available",
    remaining: "Remaining",
    spent: "Spent:",
    saveAllAllocations: "SAVE ALL ALLOCATIONS",
    other: "Other",
    allocationExceedsBalance: "Allocated amount exceeds available balance",
    // Category Group Manager
    manageCategoryGroups: "Manage Category Groups",
    createCategoryGroup: "Create Category Group",
    addCategory: "Add Category",
    categoryGroupTip:
      'You can quickly add from available templates. Existing categories will display the "Already Added" label.',
    deleteCategoryError: "An error occurred while deleting category",
    sort: "Sort",
    deleteCategory: "Delete category",
    alreadyAdded: "Already Added",
    // Help Center
    helpCenter: "Help Center",
    helpCenterContent:
      "- Set up categories and category groups to manage budget by item.\n- Allocate budget in the Edit Budget section.\n- Update wallet balance and add transactions to track income/expenses.",
    restartGuide: "Restart Guide",
    restartGuideDescription:
      "Restart the step-by-step tutorial tour for new users.",
    // Onboarding
    welcomeToFinanceTracker: "Welcome to Finance Tracker",
    smartPersonalFinanceApp: "Smart personal finance management app",
    smartSpendingManagement: "Smart Spending Management",
    trackAndAnalyzeIncomeExpenses:
      "Track and analyze income and expenses easily",
    enterIncomeAndExpenses: "Enter income and expenses",
    recordAllDailyTransactions:
      "Record all daily transactions to know where you're spending money.",
    categorizeByCategory: "Categorize by category",
    divideMoneyIntoCategories:
      "Divide money into specific categories like Food, Transportation, Entertainment...",
    viewChartsAndStatistics: "View charts and statistics",
    analyzeSpendingThroughCharts:
      "Analyze spending through visual, easy-to-understand charts.",
    keyFeatures: "Key Features",
    simpleIncomeExpenseManagement: "Simple income and expense management",
    visualEasyToUnderstandCharts: "Visual, easy-to-understand charts",
    filterAndSortTransactions: "Filter and sort transactions",
    manageMultipleWallets: "Manage multiple wallets",
    startNow: "Start now",
    zeroBasedBudgetingMethod: "Zero-based budgeting method",
    incomeMinusExpensesEqualsZero: "Income - Expenses = 0",
    everyDollarMustBeAssigned:
      'Every dollar earned must be "assigned a job" before you actually spend it.',
    createEnvelopes: 'Create "Envelopes"',
    divideMoneyIntoSpecificCategories:
      "Divide money into specific categories like Food, Transportation, Savings...",
    completeControl: "Complete Control",
    knowExactlyWhereMoneyGoes:
      "You know exactly where your money goes and can adjust flexibly.",
    benefitsOfSmartSpendingManagement: "Benefits of Smart Spending Management",
    betterSpendingControl: "Better spending control",
    saveMore: "Save more",
    achieveFinancialGoals: "Achieve financial goals",
    reduceFinancialStress: "Reduce financial stress",
    strengthenFinancialDiscipline: "Strengthen financial discipline",
    betterFuturePlanning: "Better future planning",
    readyToStartFinancialJourney: "Ready to start your financial journey?",
    startSmartFinancialManagement:
      "Start smart financial management with Finance Tracker",
    // Category Selection
    selectExpenseCategories: "Select expense categories",
    categoriesSelected: "categories selected",
    selectYourExpenseCategories: "Select your expense categories",
    incomeCategoriesAutoCreated:
      "Income categories (Salary, Bonus, Investment...) will be created automatically.",
    canEditLater: "You can edit them anytime later.",
    template1FinanceTracker: "Template 1: Finance Tracker Style",
    template1Description: "Flexible and modern financial management style",
    template2_50_30_20: "Template 2: 50/30/20",
    template2Description:
      "Budget allocation method: 50% needs, 30% wants, 20% savings",
    selectAll: "All",
    deselectAll: "Deselect",
    continueButton: "CONTINUE",
    readyToContinue: "Ready to continue?",
    skipStepHint:
      "You can skip this step and create categories later in the app",
    selectedCategoriesCount:
      "You have selected {count} categories to start financial management",
    goBack: "Go back",
    // Category Names (for templates)
    categoryRent: "Rent/Housing",
    categoryBills: "Bills",
    categoryFood: "Food & Drink",
    categoryTransportation: "Transportation",
    categoryChildren: "Children",
    categoryPets: "Pets",
    categoryDebt: "Debt/Loans",
    categoryHealthcare: "Medical/Medication",
    categoryInsurance: "Life Insurance",
    categoryCarMaintenance: "Car Maintenance",
    categoryGifts: "Gifts, Celebrations",
    categoryEducation: "Tuition, Online Courses",
    categoryShopping: "Shopping",
    categoryMassage: "Massage",
    categorySpa: "Spa",
    categoryHomeDecoration: "Home Decoration",
    categoryShortTrips: "Short Trips",
    categoryBuyHouse: "Buy House",
    categoryBuyCar: "Buy Car",
    categoryHomeRepair: "Home Repair",
    categoryEquipmentUpgrade: "Equipment Upgrade, Tools",
    categoryHousing: "Housing",
    categoryDailyFood: "Daily Food",
    categoryMandatoryInsurance: "Mandatory Insurance",
    categoryBasicMedicine: "Basic Medicine",
    categoryDiningOut: "Dining Out/Cafe",
    categoryShoppingEntertainment: "Shopping/Entertainment",
    categoryTravel: "Travel",
    categorySpaMassage: "Spa, Massage",
    categoryPersonalHobbies: "Personal Hobbies",
    categoryEmergencyFund: "Emergency Fund",
    categoryLongTermInvestment: "Long-term Investment",
    categoryEquipmentUpgradeShort: "Equipment Upgrade",
    categorySelfDevelopment: "Education / Self Development",
    // Category Groups
    groupMandatoryExpenses: "Mandatory Expenses",
    groupIrregularExpenses: "Irregular Expenses",
    groupMyJoys: "My Joys",
    groupLongTermInvestment: "Long-term Investment",
    groupEssentialNeeds: "Essential Needs (50%)",
    groupWants: "Wants (30%)",
    groupSavingsInvestment: "Savings & Investment (20%)",
    groupIncome: "Income",
    // Income Categories
    incomeSalary: "Salary",
    incomeBonus: "Bonus",
    incomeInvestment: "Investment",
    incomeOther: "Other Income",
    // Tour Guide
    tourStep1ManageGroups:
      "Manage groups and add categories from available templates.",
    tourStep2BudgetList: "View and edit budget for each category here.",
    tourStep3WalletUpdate: "Update wallet balance for accurate data.",
    tourStep4AddTransaction: "Add your first transaction.",
    tourStep5CreateWallet:
      "Create a new wallet to efficiently manage your finances.",
    finish: "Finish",
    next: "Next",
    skip: "Skip",
    // Landing Page & Login
    login: "Login",
    register: "Register",
    registerSubtitle: "Create a new account to start",
    registerFree: "Register Free",
    registerNow: "Register Now",
    registering: "Registering...",
    registerFailed: "Registration failed",
    fullName: "Full Name",
    confirmPassword: "Confirm Password",
    nameRequired: "Please enter name",
    nameMinLength: "Name is too short",
    confirmPasswordRequired: "Please confirm password",
    passwordsDontMatch: "Passwords don't match",
    alreadyHaveAccount: "Already have an account?",
    loginNow: "Log in now",
    placeholderName: "John Doe",
    landingSecurityBadge: "100% Secure & Free",
    landingHeroTitle: "Manage your finances",
    landingHeroSubtitle: "smarter",
    landingHeroDescription:
      "Track expenses, analyze trends and achieve your financial goals. All in one simple, easy-to-use app.",
    landingStartFree: "Start Now - Free",
    landingExampleIncome: "This month's income",
    landingExampleExpense: "This month's expense",
    landingFeaturesTitle: "Featured Features",
    landingFeaturesSubtitle:
      "Everything you need to manage finances effectively",
    landingFeature1Title: "Track Income & Expenses",
    landingFeature1Desc: "Record all income and expenses easily and quickly",
    landingFeature2Title: "Spending Analysis",
    landingFeature2Desc: "Visual charts help you understand your spending",
    landingFeature3Title: "Savings Goals",
    landingFeature3Desc: "Set financial goals and track your progress",
    landingFeature4Title: "Recurring Transactions",
    landingFeature4Desc:
      "Automatically record monthly recurring income and expenses",
    landingFeature5Title: "Financial Trends",
    landingFeature5Desc:
      "View income and expense trends over time for better decisions",
    landingFeature6Title: "Export Reports",
    landingFeature6Desc: "Download data as CSV or PDF for storage",
    landingBenefit1: "100% Free - No hidden fees",
    landingBenefit2: "Beautiful, easy-to-use interface",
    landingBenefit3: "Absolute information security",
    landingBenefit4: "Access anytime, anywhere",
    landingBenefit5: "Continuous feature updates",
    landingBenefit6: "Multi-device support",
    landingWhyUsTitle: "Why choose us?",
    landingCTATitle: "Ready to start your financial journey?",
    landingCTADescription:
      "Join thousands of users who have improved their finances",
    landingCTAButton: "Register Free Now",
    landingFooterText: "Smart financial management.",
    loginSubtitle: "Manage your personal finances",
    password: "Password",
    invalidEmail: "Invalid email",
    emailRequired: "Please enter email",
    passwordRequired: "Please enter password",
    passwordMinLength: "Password must be at least 6 characters",
    passwordStrengthRequirement:
      "Password must contain at least 1 uppercase letter (A-Z), 1 lowercase letter (a-z) and 1 number (0-9)",
    passwordTooWeak:
      "Password is too weak. Please use a password with uppercase, lowercase letters and numbers for better security.",
    loginFailed: "Login failed",
    loggingIn: "Logging in...",
    resetPassword: "Reset Password",
    sendCodeToEmail: "Send code to email",
    sendingCode: "Sending code...",
    verificationCode: "Verification code (6 digits)",
    newPassword: "New password",
    confirmReset: "Confirm reset",
    verificationCodeSent:
      "Verification code has been sent to your email. Please check your inbox.",
    resetPasswordSuccess: "Password reset successful.",
    resetPasswordFailed: "Password reset failed",
    sendCodeFailed: "Failed to send code",
    or: "Or",
    noAccountYet: "Don't have an account?",
    googleOAuthNotConfigured:
      "Google OAuth is not configured. Please contact administrator.",
    googleSignInInitError:
      "Unable to initialize Google Sign-In. Please reload the page.",
    // Transaction List
    transactionCount: "Transactions",
    byAmount: "By Amount",
    confirmDeleteTransaction:
      "Are you sure you want to delete this transaction?",
    // Budget Screen
    expenseManagement: "Expense Management",
    trackPersonalIncomeExpenses: "Track personal income and expenses",
    statisticalChart: "Statistical Chart",
    editBudgetAllocation: "Edit Budget Allocation",
    budgetAllocationSuccess: "Budget allocation successful!",
    budgetAllocationError: "An error occurred while saving budget allocation",
    updateBudgetSuccess: "Budget updated successfully!",
    updateBudgetError: "An error occurred while updating budget",
    initializeCategoriesError:
      "An error occurred while initializing categories. Please try again.",
    noExpenseData: "No expense data yet",
    navigateTo: "Navigate to",
    // Quick Action Modal
    whatDoYouWantToCreate: "What do you want to create?",
    transfer: "Transfer",
    // Wallet Empty States
    createWalletToStart: "Create a wallet to start managing finances",
    createFirstWalletButton: "Create first wallet",
    // Wallet Prompt Modal
    walletPromptTitle: "Create your first wallet",
    startManagingFinances: "Start managing finances",
    walletPromptDescription:
      "To add transactions, you need to create at least one wallet. Wallets help you organize and track your money.",
    manageMultipleWalletsTitle: "Manage multiple wallets",
    manageMultipleWalletsDesc: "Create multiple wallets for different purposes",
    trackBalanceTitle: "Track balance",
    trackBalanceDesc: "View the current balance of each wallet easily",
    recordTransactionsTitle: "Record transactions",
    recordTransactionsDesc:
      "After creating a wallet, you can start adding income and expense transactions",
    laterButton: "Later",
    createWalletNow: "Create wallet now",
    // Budget Screen
    editBudget: "Edit budget",
    categoriesCount: "categories",
    allocated: "Allocated:",
    budgetNotSet: "Budget not set yet",
    remainingLabel: "Remaining:",
    noCategoriesCreated: "No categories created yet",
    createCategoriesToStart:
      "Create categories to start managing budget with Zero-Based Budgeting",
    createNewCategory: "Create new category",
    selectFromTemplate: "Select from template",
    noCategoriesYet: "No categories yet. Please create categories first.",
    // Transaction Modal
    selectCategory: "Select category",
    selectWallet: "Select wallet",
    enterAmount: "Enter amount",
    yourCategories: "Your Categories",
    pleaseCreateWalletAndCategory:
      "Please create a wallet and categories before adding a transaction",
    addTransaction: "Add Transaction",
    editTransaction: "Edit Transaction",
    saveTransaction: "Save Transaction",
    updateTransaction: "Update Transaction",
    deleteTransaction: "Delete Transaction",
    note: "Note",
    addNoteForTransaction: "Add a note for the transaction...",
    loadingData: "Loading data...",
    clearAll: "Clear All",
    update: "Update",
    save: "Save",
    // Wallet Types
    mainWallet: "Main Wallet",
    bankCard: "Bank Card",
    eWallet: "E-Wallet",
    gold: "Gold",
    creditCard: "Credit Card",
    loans: "Loans",
    // Date Picker
    thisMonth: "This Month",
    previousMonth: "Previous Month",
    // Settings Screen
    dataAndBackup: "Data & Backup",
    deleteAllDataWarning:
      "Delete all wallets, categories, transactions, and budgets. This action cannot be undone.",
    accountInformation: "Account Information",
    editPersonalInformation: "Edit personal information",
    contactUs: "Contact Us",
    supportAndFeedback: "Support and feedback",
    userGuide: "User Guide",
    faqAndDocuments: "FAQ and documents",
    thisMonthOption: "This Month",
    thisYear: "This Year",
    custom: "Custom",
    to: "to",
    exportTransactions: "Export Transactions",
    exportCategories: "Export Categories",
    exportWallets: "Export Wallets",
    exportReports: "Export Reports",
    yourName: "Your Name",
    saveButton: "Save",
    cancelButton: "Cancel",
    noDataToExport: "No data to export",
    confirmLogout: "Are you sure you want to logout?",
    updateProfileError:
      "An error occurred while saving information. Please try again.",
    deleteDataWarning:
      "⚠️ WARNING\n\nAre you sure you want to delete ALL financial data?\n\nThis action will:\n• Delete all wallets, categories, transactions\n• Delete all budgets and statistics\n• CANNOT BE UNDONE\n\nEnter 'DELETE' to confirm:",
    deleteDataConfirmCode: "DELETE",
    deleteDataError: "An error occurred while deleting data. Please try again.",
    deleteDataConfirmInvalid: "Invalid confirmation. Canceling data deletion.",
    // Common
    close: "Close",
    loading: "Loading...",
    error: "Error",
    success: "Success",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("app_language");
    return saved || "vi";
  });

  // Listen for storage events and custom events to sync language changes
  useEffect(() => {
    const handleStorageChange = (e) => {
      if (e.key === "app_language" && e.newValue) {
        setLanguage(e.newValue);
      }
    };

    const handleLanguageChange = (e) => {
      if (e.detail && e.detail.language) {
        setLanguage(e.detail.language);
      }
    };

    window.addEventListener("storage", handleStorageChange);
    window.addEventListener("languagechange", handleLanguageChange);

    return () => {
      window.removeEventListener("storage", handleStorageChange);
      window.removeEventListener("languagechange", handleLanguageChange);
    };
  }, []);

  useEffect(() => {
    localStorage.setItem("app_language", language);
    // Mark as manually set when user explicitly changes language
    localStorage.setItem("language_manually_set", "true");
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
